title: Executions in the United States since 1977
description: Looking into age, sex and the methods used in United States executions since 1977. Will be breaking it down into states and regions where these executions we're preformed and any trends that follow. 
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CHANGELOG.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - LICENSE
  - PULL_REQUEST_TEMPLATE.md
  - README.md
theme: jekyll-theme-time-machine
source: ./pages
collections_dir: ./pages
includes_dir: _includes
