title: Executions in the United States since 1977
description: Looking into age, location and the methods used in United States executions since 1977. 
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CHANGELOG.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - LICENSE
  - PULL_REQUEST_TEMPLATE.md
  - README.md
theme: jekyll-theme-midnight
source: ./pages
collections_dir: ./pages
includes_dir: _includes
